//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridgeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_tbl
    {
        public int Product_Id { get; set; }
        public string Product_Categories { get; set; }
        public string Product_Name { get; set; }
        public decimal Price { get; set; }
        public string Product_Discription { get; set; }
        public Nullable<System.DateTime> Product_MFG_Date { get; set; }
    }
}
